### List available API calls
GET http://localhost:8080/

### Get a random math fact
GET http://localhost:8080/api/numbers/math/random

### Most recent launches
GET http://localhost:8080/api/spacex/launches

### Details about a specific launch
GET http://localhost:8080/api/spacex/launches/5eb87cd9ffd86e000604b32a

### Get all rockets
GET http://localhost:8080/api/spacex/rockets

### Get a specific rocket
GET http://localhost:8080/api/spacex/rockets/5e9d0d95eda69955f709d1eb
